---
- hosts: all
  become: true

  tasks:

    - name: copy configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=True
      with_items:
        - { src: '/tmp/config/rc.conf', dest: '/etc/rc.conf' }

    - name: Bring up network
      command:  "{{ item }}"
      with_items: 
        - /etc/rc.d/netif restart vtnet1
        - /etc/rc.d/netif restart vtnet1.2002
        - /etc/rc.d/netif restart vtnet1.2006
        - /etc/rc.d/routing restart
        - service dhclient restart vtnet0
        # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # /etc/rc.d/routing restart is a jackass, it clobbers dhcp routes but 
        # does not bother to put them back, so we need to restart dhclient to 
        # get them back ourselves

    - name: make dnet dir
      file:
        path: /home/rvn/.go/src/github.com/deter-project/switch-drivers
        state: directory

    - name: setup link dnet
      file:
        src: /opt/deter/switch-drivers/snmp
        dest: /home/rvn/.go/src/github.com/deter-project/switch-drivers/snmp
        state: link
    
    - name: install software
      package:
        name: "{{item}}"
        state: present
        use: pkgng
      with_items:
        - lldpd
        - go
        - git

    - name: make sure bashrc exists
      file:
        path: /home/rvn/.bashrc
        state: touch
    
    - name: configure go paths
      lineinfile:
        dest: /home/rvn/.bashrc
        line: "{{ item }}"
      with_items:
        - "export PATH=~/scripts:$PATH"
        - "export GOPATH=~/.go"
        - "export PATH=$GOPATH/bin:$PATH"

    - name: install go dependencies
      shell: go get {{ item }}
      environment:
        GOPATH: /home/rvn/.go
      with_items:
        - github.com/fatih/color
        - github.com/soniah/gosnmp

    - name: Make testbed directory
      file:
        path: /usr/testbed
        state: directory
    
    - name: Link testbed source
      file:
        src: /opt/deter/testbed
        dest: /usr/testbed/src
        state: link
    
    
    - name: Softlink legacy perl location
      file:
        src: /usr/local/bin/perl
        dest: /usr/bin/perl
        state: link

    #TODO placeholder for installing packages, anything that goes here should
    #     be ploped into package-build
    #
    - name: Install requirements
      command: pkg install -y {{ item }}
      with_items:
        - p5-SNMP-Util
        - go
