---
- hosts: all
  become: true

  vars:
    mirror: mirror.deterlab.net

  tasks:

    - name: Tell resolvconf to shove it
      copy:
        src: /tmp/config/resolvconf.conf
        dest: /etc/resolvconf.conf
        remote_src: true

    - name: Setup resolv.conf
      copy:
        src: /tmp/config/resolv.conf
        dest: /etc/resolv.conf
        remote_src: true

    - name: Add stuff to testbed dns
      lineinfile:
        dest: /usr/local/etc/namedb/vbed3.deterlab.net.internal.db.head
        line: "{{ item }}"
      with_items:
        - "stem IN A 192.168.254.1"
        - "leaf IN A 192.168.254.2"

    - name: Re-initialize testbed dns
      command:  /usr/testbed/sbin/named_setup

    - name: Set up database
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/initdb.sql
    
    - name: Fetch Node Images
      get_url:
        url: "http://{{ mirror }}/deter/images/{{ item }}"
        dest: "/usr/testbed/images/{{ item }}"
      with_items:
        - Ubuntu1404-64-STD.ndz
        - Ubuntu1604-STD.ndz

    - name: Fetch Image Temp DBs
      get_url:
        url: http://{{ mirror }}/deter/images/tempdb.sql
        dest: /tmp/tempdb.sql

    - name: Load image descriptors into DB
      command: perl /usr/testbed/obj/install/load-descriptors /tmp/tempdb.sql

    - name: Add qnode type to DB
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/qnode.sql

    - name: Create battlestar project
      command: su elabman -c "/tmp/config/first_project.sh"

    - name: Commission Adama
      command: "{{ item }}"
      with_items:
        - /usr/testbed/sbin/wap /usr/testbed/sbin/tbadmin adama
        - chsh -s /usr/local/bin/bash adama

    - name: clear default vlan from leaf
      shell: /usr/testbed/bin/dsnmp leaf vlan 1 clear-all

