---
- hosts: all
  become: true

  tasks:
    - apt: name={{item}} state=latest
      with_items:
        - vim
        - golang
        - bash-completion
        - git
        - build-essential

    - name: copy configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=True
      with_items:
        - { src: '/tmp/config/interfaces', dest: '/etc/network/interfaces' }
        - { src: '/tmp/config/snmpd.conf', dest: '/etc/snmp/snmpd.conf' }
        - { src: '/tmp/config/lldpd.conf', dest: '/etc/lldpd.d/lldpd.conf' }
        - { src: '/tmp/config/lldpd_default', dest: '/etc/default/lldpd' }

    - name: bring up interfaces
      command: ifup -a

    - name: restart lldpd
      service:
        name: lldpd
        state: restarted
    
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted

    - file:
        path: /root/.go/src/github.com/rcgoodfellow
        state: directory

    - file:
        src: "/opt/{{item}}"
        dest: "/root/.go/src/github.com/rcgoodfellow/{{item}}"
        state: link
      with_items:
        - agx
        - netlink

    - lineinfile:
        line: "{{ item }}"
        path: /root/.bashrc
      with_items:
        - export GOPATH=/root/.go
        - export GOBIN=/root/.go/bin
        - export PATH=/root/.go/bin:$PATH
    
    - shell: go get {{item}}
      environment:
        GOPATH: /root/.go
      with_items:
        - github.com/vishvananda/netlink/nl

    - shell: go install
      args:
        chdir: /root/.go/src/github.com/rcgoodfellow/agx/qbridge
      environment:
        GOPATH: /root/.go
        GOBIN: /root/.go/bin

    - shell: nohup /root/.go/bin/qbridge > /dev/null 2>&1  &
